# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Publish Python Package to 

on:
  release:
    types: [created]

jobs:
  deploy:

    strategy:
      matrix:
        os:
          # Using ubuntu-18.04 specifically because that's our deployment target
          - ubuntu-18.04
          # Using macos-latest vaguely because this is our development environment
          # - macos-latest
        # Build for Python >=3.6
        python-version: [ 3.6, 3.7, 3.8 ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends build-essential pkg-config liblz4-dev libhdf5-dev libhdf5-serial-dev

      - name: Install Python build dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements/build.txt ]; then pip install -r requirements/build.txt; fi

      - name: Build and publish Python distribution
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py bdist_wheel
          twine upload dist/*
